# Generated by Django 4.2.6 on 2023-10-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('CodCurso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Credito', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('CodDocente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Apellido', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('CodEstudiante', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('AñoIngreso', models.IntegerField()),
                ('Apellido', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AñoAcademico', models.IntegerField()),
                ('Ciclo', models.CharField(max_length=10)),
                ('Fecha', models.DateField()),
                ('CodigoCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCursos.curso')),
                ('CodigoDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCursos.docente')),
                ('CodigoEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCursos.estudiante')),
            ],
        ),
    ]
