# Generated by Django 4.2.6 on 2023-10-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCursos', '0002_rename_añoingreso_estudiante_anioingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='CodCurso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docente',
            name='CodDocente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='AnioIngreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='CodEstudiante',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='AnioAcademico',
            field=models.DateField(),
        ),
    ]
