# Generated by Django 4.2.6 on 2023-10-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCursos', '0003_alter_curso_codcurso_alter_docente_coddocente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='AnioIngreso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='Fecha',
            field=models.IntegerField(),
        ),
    ]
