# Generated by Django 4.2.6 on 2023-10-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCursos', '0004_alter_estudiante_anioingreso_alter_matricula_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='AnioAcademico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
