# Generated by Django 4.2.6 on 2023-10-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCursos', '0005_alter_matricula_anioacademico_alter_matricula_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='id',
        ),
        migrations.AddField(
            model_name='matricula',
            name='matricula_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
